name: Update LeetCode Stats

on:
  schedule:
    - cron: "0 * * * *"  # This runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate LeetCode Stats
        uses: PlatinumJ/leetcode-readme-stats@master
        with:
          LEETCODE_USERNAME: Rutuja_kokate
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add README.md
          git commit -m "Update LeetCode stats" || echo "No changes to commit"
          git push
