name: Update LeetCode status

on:
  schedule:
    - cron: "0 6 * * *"   # daily at 06:00 UTC; change if you like
  workflow_dispatch:       # allows manual run from Actions UI
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install requirements
        run: python -m pip install --upgrade pip requests

      - name: Run leetcode updater
        env:
          LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}
          LEETCODE_USERNAME: ${{ secrets.LEETCODE_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/update_leetcode.py

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add README.md
            git commit -m "chore: update LeetCode solved list (automated)"
            git push origin HEAD
          else
            echo "No changes to commit"
          fi
